version: '3.7'
services:

  mongo_6:
    container_name: mongo_6
    image: mongo:6.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydb
    # volumes:
    #   - './mongodb_data:/data/db'
    #   - './mongodb_config:/data/configdb'
    # networks:
    #   - network1

  # mongo-express:
  #   image: mongo-express:latest
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/my_db
  #   depends_on:
  #     - mongo_6

# networks:
#   network1:
#     name: mi_red
#     external: true